# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code @ Belka
email: hello@belka.us
description: > # this means to ignore newlines until "baseurl:"
  We are a design and software development team specialized in custom solutions.
  We are passionate about creating iOS, Android and Web apps .
  We have proudly helped to innovate and implement new technologies enterprises, startups and some crazy visionary.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://belka.us" # the base hostname & protocol for your site
twitter_username: BelkaDigitalLab

# Build settings
markdown: kramdown

colors:  #in hex code if not noted else
  primary: "#FFFFFF" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384052" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
